dc_name: hetzner
base_dir: config
org_name: chaordic

server_groups:
  server:
    num: 3
    lb_target: false
    instance_type: cx21
 #   volumes: 
 #   - name: "data_vol"
 #     path: /opt/nomad_server_data
 #     size: 20
 #     owner: www-data
  agent:
    num: 2
    lb_target: true # should probably be is_lb_target instead, more natural
    instance_type: cx21

providers:
  ansible:
    sudo_user: root
    ssh_key_path: /home/wfaler/.ssh/id_rsa
    playbooks: 
    - file: playbooks/k3s.yml
      vars: 
        network_interface: ens10
    global_vars:
      network_interface: ens10

cloud_provider_config:
  provider: hetzner
  allowed_ips:
    - 178.197.214.192/32
  provider_settings:
    # parameterise OS family?
    location: fsn1
    ssh_keys:
    - wfaler@chaordic.io
    load_balancer_type: lb11
    ssl_certificate_ids:
    - 1232582 # use Hetzner hcloud CLI tool to retrieve numeric ID: "hcloud certificate list"
    resource_names:
      base_server_name: prod
      firewall_name: prod_firewall
      network_name: prod_network
